/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: authentication.proto */

#ifndef PROTOBUF_C_authentication_2eproto__INCLUDED
#define PROTOBUF_C_authentication_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _LoginRequest LoginRequest;
typedef struct _SignupRequest SignupRequest;
typedef struct _AuthenticationResponse AuthenticationResponse;


/* --- enums --- */


/* --- messages --- */

struct  _LoginRequest
{
  ProtobufCMessage base;
  ProtobufCBinaryData messagetype;
  char *username;
  char *password;
};
#define LOGIN_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&login_request__descriptor) \
    , {0,NULL}, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _SignupRequest
{
  ProtobufCMessage base;
  char *username;
  char *password;
  char *email;
};
#define SIGNUP_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&signup_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _AuthenticationResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean success;
  char *message;
};
#define AUTHENTICATION_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&authentication_response__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


/* LoginRequest methods */
void   login_request__init
                     (LoginRequest         *message);
size_t login_request__get_packed_size
                     (const LoginRequest   *message);
size_t login_request__pack
                     (const LoginRequest   *message,
                      uint8_t             *out);
size_t login_request__pack_to_buffer
                     (const LoginRequest   *message,
                      ProtobufCBuffer     *buffer);
LoginRequest *
       login_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   login_request__free_unpacked
                     (LoginRequest *message,
                      ProtobufCAllocator *allocator);
/* SignupRequest methods */
void   signup_request__init
                     (SignupRequest         *message);
size_t signup_request__get_packed_size
                     (const SignupRequest   *message);
size_t signup_request__pack
                     (const SignupRequest   *message,
                      uint8_t             *out);
size_t signup_request__pack_to_buffer
                     (const SignupRequest   *message,
                      ProtobufCBuffer     *buffer);
SignupRequest *
       signup_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   signup_request__free_unpacked
                     (SignupRequest *message,
                      ProtobufCAllocator *allocator);
/* AuthenticationResponse methods */
void   authentication_response__init
                     (AuthenticationResponse         *message);
size_t authentication_response__get_packed_size
                     (const AuthenticationResponse   *message);
size_t authentication_response__pack
                     (const AuthenticationResponse   *message,
                      uint8_t             *out);
size_t authentication_response__pack_to_buffer
                     (const AuthenticationResponse   *message,
                      ProtobufCBuffer     *buffer);
AuthenticationResponse *
       authentication_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   authentication_response__free_unpacked
                     (AuthenticationResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*LoginRequest_Closure)
                 (const LoginRequest *message,
                  void *closure_data);
typedef void (*SignupRequest_Closure)
                 (const SignupRequest *message,
                  void *closure_data);
typedef void (*AuthenticationResponse_Closure)
                 (const AuthenticationResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor login_request__descriptor;
extern const ProtobufCMessageDescriptor signup_request__descriptor;
extern const ProtobufCMessageDescriptor authentication_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_authentication_2eproto__INCLUDED */
