/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: authentication.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "authentication.pb-c.h"
void   login_request__init
                     (LoginRequest         *message)
{
  static const LoginRequest init_value = LOGIN_REQUEST__INIT;
  *message = init_value;
}
size_t login_request__get_packed_size
                     (const LoginRequest *message)
{
  assert(message->base.descriptor == &login_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t login_request__pack
                     (const LoginRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &login_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t login_request__pack_to_buffer
                     (const LoginRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &login_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoginRequest *
       login_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoginRequest *)
     protobuf_c_message_unpack (&login_request__descriptor,
                                allocator, len, data);
}
void   login_request__free_unpacked
                     (LoginRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &login_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   signup_request__init
                     (SignupRequest         *message)
{
  static const SignupRequest init_value = SIGNUP_REQUEST__INIT;
  *message = init_value;
}
size_t signup_request__get_packed_size
                     (const SignupRequest *message)
{
  assert(message->base.descriptor == &signup_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t signup_request__pack
                     (const SignupRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &signup_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t signup_request__pack_to_buffer
                     (const SignupRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &signup_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SignupRequest *
       signup_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SignupRequest *)
     protobuf_c_message_unpack (&signup_request__descriptor,
                                allocator, len, data);
}
void   signup_request__free_unpacked
                     (SignupRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &signup_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   authentication_response__init
                     (AuthenticationResponse         *message)
{
  static const AuthenticationResponse init_value = AUTHENTICATION_RESPONSE__INIT;
  *message = init_value;
}
size_t authentication_response__get_packed_size
                     (const AuthenticationResponse *message)
{
  assert(message->base.descriptor == &authentication_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t authentication_response__pack
                     (const AuthenticationResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &authentication_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t authentication_response__pack_to_buffer
                     (const AuthenticationResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &authentication_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AuthenticationResponse *
       authentication_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AuthenticationResponse *)
     protobuf_c_message_unpack (&authentication_response__descriptor,
                                allocator, len, data);
}
void   authentication_response__free_unpacked
                     (AuthenticationResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &authentication_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor login_request__field_descriptors[3] =
{
  {
    "messagetype",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(LoginRequest, messagetype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "username",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LoginRequest, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LoginRequest, password),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned login_request__field_indices_by_name[] = {
  0,   /* field[0] = messagetype */
  2,   /* field[2] = password */
  1,   /* field[1] = username */
};
static const ProtobufCIntRange login_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor login_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LoginRequest",
  "LoginRequest",
  "LoginRequest",
  "",
  sizeof(LoginRequest),
  3,
  login_request__field_descriptors,
  login_request__field_indices_by_name,
  1,  login_request__number_ranges,
  (ProtobufCMessageInit) login_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor signup_request__field_descriptors[3] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SignupRequest, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SignupRequest, password),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "email",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SignupRequest, email),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned signup_request__field_indices_by_name[] = {
  2,   /* field[2] = email */
  1,   /* field[1] = password */
  0,   /* field[0] = username */
};
static const ProtobufCIntRange signup_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor signup_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SignupRequest",
  "SignupRequest",
  "SignupRequest",
  "",
  sizeof(SignupRequest),
  3,
  signup_request__field_descriptors,
  signup_request__field_indices_by_name,
  1,  signup_request__number_ranges,
  (ProtobufCMessageInit) signup_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor authentication_response__field_descriptors[2] =
{
  {
    "success",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(AuthenticationResponse, success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthenticationResponse, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned authentication_response__field_indices_by_name[] = {
  1,   /* field[1] = message */
  0,   /* field[0] = success */
};
static const ProtobufCIntRange authentication_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor authentication_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AuthenticationResponse",
  "AuthenticationResponse",
  "AuthenticationResponse",
  "",
  sizeof(AuthenticationResponse),
  2,
  authentication_response__field_descriptors,
  authentication_response__field_indices_by_name,
  1,  authentication_response__number_ranges,
  (ProtobufCMessageInit) authentication_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
